import { Certification } from "@/types";

const CERTIFICATIONS_DATA: Certification[] = [
  {
    title: "Google Advanced Data Analytics Professional Certificate",
    description:
      "In-depth data analytics techniques using Google tools and techniques",
    image: "/certifications/google-advanced-data-analytics.jpeg",
    category: "Data Analytics",
    issuer: "Google",
    date: "May 2025",
    verifyUrl: "https://coursera.org/share/346e100a7b5e9f3fd17968d9d5358832",
    skills: [],
  },
  {
    title: "Meta Full-Stack Engineer Professional Certificate",
    description:
      "Full-stack development skills using frontend and backend tools",
    image: "/certifications/meta-full-stack.jpeg",
    category: "Development",
    issuer: "Meta",
    date: "September 2024",
    verifyUrl:
      "https://www.credly.com/badges/d0ea6679-b3f8-4541-93f2-0f2e12ae4f05/public_url",
    skills: [],
  },
  {
    title: "Microsoft Technical Assistant - Python",
    description: "Introduction to programming concepts with Python",
    image: "/certifications/ms-python-intro.jpeg",
    category: "Programming",
    issuer: "Microsoft",
    date: "February 2019",
    verifyUrl:
      "https://www.credly.com/badges/1833ec15-a3c5-4fc9-9324-f4df31320587/public_url",
    skills: [],
  },
  {
    title: "Natural Language Processing Specialization Certificate",
    description:
      "Techniques for working with and understanding human language data",
    image: "/certifications/nlp-deeplearning.jpeg",
    category: "NLP",
    issuer: "DeepLearning.AI",
    date: "March 2025",
    verifyUrl: "https://coursera.org/share/040149960ded839ca1306fb439f5f004",
    skills: [],
  },
  {
    title: "IBM Generative AI Engineering Professional Certificate",
    description:
      "Professional-level certification in generative AI engineering concepts and techniques",
    image: "/certifications/ibm-gen-ai.jpeg",
    category: "AI",
    issuer: "IBM",
    date: "May 2025",
    verifyUrl: "https://coursera.org/share/d972909516f72e67c7f80c327ffd7f6e",
    skills: [],
  },
  {
    title: "IBM Data Science Professional Certificate",
    description:
      "Professional-level certification in data science concepts and techniques",
    image: "/certifications/ibm-data-science-professional.jpeg",
    category: "Data Science",
    issuer: "IBM",
    date: "April 2024",
    verifyUrl: "https://coursera.org/share/149a8e0c3a28da2da815ed9cfc404890",
    skills: [],
  },
  {
    title: "Deep Learning Specialization Certificate",
    description: "Mastering neural networks and deep learning frameworks",
    image: "/certifications/deep-learning-deeplearningai.jpeg",
    category: "Data Science",
    issuer: "DeepLearning.AI",
    date: "April 2025",
    verifyUrl: "https://coursera.org/share/f28386d126df1e94e3f11ce6e9155106",
    skills: [],
  },
  {
    title: "IBM AI Developer Professional Certificate",
    description: "Professional-level certification in AI development",
    image: "/certifications/ibm-ai-developer.jpeg",
    category: "AI",
    issuer: "IBM",
    date: "May 2025",
    verifyUrl: "https://coursera.org/share/5c9cacb041eb74c459c5a5265a9ff909",
    skills: [],
  },
  {
    title: "TensorFlow Developer Professional Certificate",
    description: "Building machine learning models with TensorFlow",
    image: "/certifications/tensorflow-developer.jpeg",
    category: "Data Science",
    issuer: "DeepLearning.AI",
    date: "June 2024",
    verifyUrl: "https://coursera.org/share/7f15c2bcda8ee858d19e5f119bd873e4",
    skills: [],
  },
  {
    title: "IBM AI Engineering Professional Certificate",
    description:
      "Professional-level certification in AI engineering concepts and techniques",
    image: "/certifications/ibm-ai-engineering.jpeg",
    category: "AI",
    issuer: "IBM",
    date: "May 2025",
    verifyUrl: "https://coursera.org/share/cc55df4123df7d2de08b44bacc65e2fc",
    skills: [],
  },
  {
    title: "AI Engineering Specialization Certificate",
    description:
      "Advanced AI engineering skills including deploying models and systems",
    image: "/certifications/ai-engineering-scrimba.jpeg",
    category: "AI",
    issuer: "Scrimba",
    date: "April 2025",
    verifyUrl: "https://coursera.org/share/a23572603fe2b3caa03a6c62f0a247bc",
    skills: [],
  },
  {
    title: "Google Business Intelligence Professional Certificate",
    description:
      "Skills in data modeling and extract, transform, load (ETL) processes, data visualizations and dashboards",
    image: "/certifications/google-bi.jpeg",
    category: "Data Analytics",
    issuer: "Google",
    date: "May 2025",
    verifyUrl: "https://coursera.org/share/346f886deb4aef0ffcbbbc9dc009be02",
    skills: [],
  },
  {
    title: "Meta Data Analyst Professional Certificate",
    description:
      "Skills in data analysis using popular tools like SQL and Python",
    image: "/certifications/meta-data-analyst.jpeg",
    category: "Data Analytics",
    issuer: "Meta",
    date: "June 2024",
    verifyUrl: "https://coursera.org/share/4efa778578d720750f6d16edf5720e12",
    skills: [],
  },
  {
    title: "Meta Generalist Software Engineer Professional Certificate",
    description:
      "Foundational software engineering skills across web, mobile, and backend development",
    image: "/certifications/meta-generalist.jpeg",
    category: "Development",
    issuer: "Meta",
    date: "September 2024",
    verifyUrl:
      "https://www.credly.com/badges/07db21a8-6387-4db2-b051-b44530e8da14/public_url",
    skills: [],
  },
  {
    title: "Meta Back-End Developer Professional Certificate",
    description:
      "Building scalable back-end services using modern technologies",
    image: "/certifications/meta-backend-developer.jpeg",
    category: "Development",
    issuer: "Meta",
    date: "September 2024",
    verifyUrl: "https://coursera.org/share/81267c202ba1d6e8bc9570fe8b870f7b",
    skills: [],
  },
  {
    title: "Meta Front-End Developer Professional Certificate",
    description: "Developing modern, responsive front-end web applications",
    image: "/certifications/meta-frontend-developer.jpeg",
    category: "Development",
    issuer: "Meta",
    date: "August 2024",
    verifyUrl: "https://coursera.org/share/341a91f1a1dbfea37b02daedaee5134c",
    skills: [],
  },
  {
    title: "Meta iOS Developer Professional Certificate",
    description: "Skills for developing native mobile apps for iOS platforms",
    image: "/certifications/meta-ios-developer.jpeg",
    category: "Development",
    issuer: "Meta",
    date: "March 2025",
    verifyUrl: "https://coursera.org/share/8bcf7607f6ab98b6e83f1c2208f17e8d",
    skills: [],
  },
  {
    title: "Meta Database Engineer Professional Certificate",
    description: "Expertise in database management, design, and optimization",
    image: "/certifications/meta-database-engineer.jpeg",
    category: "Development",
    issuer: "Meta",
    date: "August 2024",
    verifyUrl: "https://coursera.org/share/99b6a054fc6f0418f2712e16f58e13b6",
    skills: [],
  },
  {
    title: "Meta React Native Professional Certificate",
    description: "Building cross-platform mobile apps using React Native",
    image: "/certifications/meta-react-native.jpeg",
    category: "Development",
    issuer: "Meta",
    date: "April 2025",
    verifyUrl: "https://coursera.org/share/990c4f35558a7ed5c2a9ac3bd6195331",
    skills: [],
  },
  {
    title:
      "IBM Deep Learning with PyTorch, Keras and Tensorflow Professional Certificate",
    description:
      "Hands-on experience with deep learning frameworks and applications",
    image: "/certifications/ibm-deep-learning.jpeg",
    category: "Data Science",
    issuer: "IBM",
    date: "May 2025",
    verifyUrl: "https://coursera.org/share/23bc35a83b702b8ab684d429d9c560af",
    skills: [],
  },
  {
    title: "IBM Generative AI Engineering with LLMs Specialization Certificate",
    description:
      "Advanced specialization in generative AI engineering with large language models",
    image: "/certifications/ibm-gen-ai-specl.jpeg",
    category: "AI",
    issuer: "IBM",
    date: "May 2025",
    verifyUrl: "https://coursera.org/share/cac008f89b81477d4f1753e14f4e77a7",
    skills: [],
  },
  {
    title: "AI Foundations for Everyone Specialization Certificate",
    description:
      "Fundamentals of Artificial Intelligence with real-world applications",
    image: "/certifications/ai-foundations-ibm.jpeg",
    category: "AI",
    issuer: "IBM",
    date: "May 2025",
    verifyUrl: "https://coursera.org/share/6e53f87216b112ef31002b58b967d1d2",
    skills: [],
  },
  {
    title: "Applied Data Science Specialization Certificate",
    description: "Hands-on skills in data science with real-world applications",
    image: "/certifications/applied-data-science-ibm.jpeg",
    category: "Data Science",
    issuer: "IBM",
    date: "April 2025",
    verifyUrl: "https://coursera.org/share/0ae48e41adfeaac5d72bd5d97db575f7",
    skills: [],
  },
  {
    title: "Data Science Fundamentals Specialization Certificate",
    description: "Introduction to data science concepts and techniques",
    image: "/certifications/data-science-fundamentals-ibm.jpeg",
    category: "Data Science",
    issuer: "IBM",
    date: "April 2025",
    verifyUrl: "https://coursera.org/share/04967f3791a286a94b6e10de1ba00ca2",
    skills: [],
  },
  {
    title: "Introduction to Data Science Specialization Certificate",
    description: "Learn the basic techniques in data science and analysis",
    image: "/certifications/intro-data-science-ibm.jpeg",
    category: "Data Science",
    issuer: "IBM",
    date: "April 2025",
    verifyUrl: "https://coursera.org/share/888edcce6d11ddf4fce4bcfe273ad2cb",
    skills: [],
  },
  {
    title: "Programming with Python",
    description: "Learning Python programming with practical applications",
    image: "/certifications/python-programming.jpeg",
    category: "Programming",
    issuer: "Internshala",
    date: "May 2018",
    verifyUrl:
      "https://trainings.internshala.com/verify_certificate?certificate_number=293407C2-1D4F-23E6-2E9F-7E9741AE8D05",
    skills: [],
  },
  {
    title: "Android App Development",
    description: "Learn Android app development from scratch",
    image: "/certifications/android-development.jpeg",
    category: "Development",
    issuer: "Internshala",
    date: "August 2018",
    verifyUrl:
      "https://trainings.internshala.com/verify_certificate?certificate_number=1C902E66-2CF5-8E33-1CEC-8E21D72C320E",
    skills: [],
  },
  {
    title: "Web Development",
    description: "Web development concepts including front-end and back-end",
    image: "/certifications/web-development.jpeg",
    category: "Development",
    issuer: "Internshala",
    date: "August 2018",
    verifyUrl:
      "https://trainings.internshala.com/verify_certificate?certificate_number=FC2CBE09-DB92-DB86-E677-45C49AD040C4",
    skills: [],
  },
  {
    title: "Google Agile Essentials",
    description:
      "Agile methodologies in a data-driven world for teams and projects",
    image: "/certifications/google-agile-essentials.jpeg",
    category: "Programming",
    issuer: "Google",
    date: "April 2025",
    verifyUrl: "https://coursera.org/share/d0bf783b5841dd5925e03adadd5951e6",
    skills: [],
  },
  {
    title: "Google AI Essentials",
    description:
      "Essentials of AI, its applications, and how it's transforming industries",
    image: "/certifications/google-ai-essentials.jpeg",
    category: "AI",
    issuer: "Google",
    date: "April 2025",
    verifyUrl: "https://coursera.org/share/6315a13e1afcce760ad35dd5f7f78693",
    skills: [],
  },
  {
    title: "Google Prompting Essentials",
    description: "How to effectively use prompting techniques for AI models",
    image: "/certifications/google-prompting-essentials.jpeg",
    category: "AI",
    issuer: "Google",
    date: "April 2025",
    verifyUrl: "https://coursera.org/share/b02287c610f94c5265d5ab58aa3a84ef",
    skills: [],
  },
  {
    title: "Python for Time Series Data Analysis",
    description: "Time series data analysis using Python libraries",
    image: "/certifications/python-time-series.jpeg",
    category: "Data Science",
    issuer: "Udemy",
    date: "May 2024",
    verifyUrl: "https://ude.my/UC-57120834-fdec-470a-a010-1a95c8af3a60",
    skills: [],
  },
  {
    title: "Data Science for Business | 6 Real-world Case Studies",
    description:
      "Practical data science skills for solving real-world business problems",
    image: "/certifications/data-science-business.jpeg",
    category: "Data Science",
    issuer: "Udemy",
    date: "April 2024",
    verifyUrl: "https://ude.my/UC-0891c544-96af-4898-9786-2a9ab58cafe0",
    skills: [],
  },
  {
    title: "Remix.js - The Practical Guide",
    description: "Learn Remix.js for modern web development",
    image: "/certifications/remixjs-guide.jpeg",
    category: "Development",
    issuer: "Udemy",
    date: "January 2024",
    verifyUrl: "https://ude.my/UC-dd80b08c-1569-4279-af3e-3cfaa626b397",
    skills: [],
  },
  {
    title: "Flutter & Dart - The Complete Guide",
    description: "Building mobile apps with Flutter and Dart",
    image: "/certifications/flutter-dart-guide.jpeg",
    category: "Development",
    issuer: "Udemy",
    date: "March 2022",
    verifyUrl: "https://ude.my/UC-c08ad4d7-97ef-49fd-87fa-c0ab50448b30",
    skills: [],
  },
  {
    title: "Docker & Kubernetes: The Practical Guide",
    description:
      "Learn containerization and orchestration with Docker and Kubernetes",
    image: "/certifications/docker-kubernetes-guide.jpeg",
    category: "DevOps & Cloud",
    issuer: "Udemy",
    date: "February 2022",
    verifyUrl: "https://ude.my/UC-794982de-8a95-4264-935d-5f43a97906d3",
    skills: [],
  },
  {
    title: "Next.js & React - The Complete Guide",
    description: "Learn to build full-stack web apps with React and Next.js",
    image: "/certifications/nextjs-react-guide.jpeg",
    category: "Development",
    issuer: "Udemy",
    date: "February 2022",
    verifyUrl: "https://ude.my/UC-91a4f742-1cb7-439a-a271-62a3da624dff",
    skills: [],
  },
  {
    title: "Complete Guide to Elasticsearch",
    description: "Master Elasticsearch for real-time search and analytics",
    image: "/certifications/elasticsearch-guide.jpeg",
    category: "ELK Stack",
    issuer: "Udemy",
    date: "January 2022",
    verifyUrl: "https://ude.my/UC-df7d839e-7ac5-4ab7-855e-4ddb4459ae39",
    skills: [],
  },
  {
    title: "Data Processing with Logstash (and Filebeat)",
    description:
      "Learn data processing and transformation with Logstash and Filebeat",
    image: "/certifications/logstash-filebeat.jpeg",
    category: "ELK Stack",
    issuer: "Udemy",
    date: "January 2022",
    verifyUrl: "https://ude.my/UC-9f98f9e3-e2c2-40fc-a16f-03486919a426",
    skills: [],
  },
  {
    title: "Data Visualization with Kibana",
    description:
      "Create interactive dashboards and data visualizations with Kibana",
    image: "/certifications/kibana-data-viz.jpeg",
    category: "ELK Stack",
    issuer: "Udemy",
    date: "January 2022",
    verifyUrl: "https://ude.my/UC-1945ea07-00e9-487f-8f79-fafd5aa6c0f6",
    skills: [],
  },
  {
    title: "NestJS: The Complete Developer's Guide",
    description:
      "Learn NestJS for building server-side applications with TypeScript",
    image: "/certifications/nestjs-guide.jpeg",
    category: "Development",
    issuer: "Udemy",
    date: "December 2021",
    verifyUrl: "https://ude.my/UC-57e00c96-b987-48bf-a50a-f1f7094f49df",
    skills: [],
  },
  {
    title: "The Complete React Developer Course (w/ Hooks and Redux)",
    description: "Building scalable React applications with hooks and Redux",
    image: "/certifications/react-developer-course.jpeg",
    category: "Development",
    issuer: "Udemy",
    date: "April 2021",
    verifyUrl: "https://ude.my/UC-446db888-a15b-4093-ad1f-b67d5d01ec1c",
    skills: [],
  },
  {
    title: "NodeJS - The Complete Guide (MVC, REST APIs, GraphQL, Deno)",
    description: "Learn Node.js for back-end development with modern tools",
    image: "/certifications/nodejs-guide.jpeg",
    category: "Development",
    issuer: "Udemy",
    date: "January 2021",
    verifyUrl: "https://ude.my/UC-7050f2b3-2f9d-4fe2-aa9b-7cf04ea6d170",
    skills: [],
  },
  {
    title: "The Complete JavaScript Course 2021: From Zero to Expert!",
    description:
      "Comprehensive JavaScript course for front-end and back-end development",
    image: "/certifications/javascript-complete-course.jpeg",
    category: "Programming",
    issuer: "Udemy",
    date: "December 2020",
    verifyUrl: "https://ude.my/UC-d5230bfa-946a-4d87-8e08-bb4ec325de0e",
    skills: [],
  },
];

export const CERTIFICATIONS: Certification[] = CERTIFICATIONS_DATA.map(
  (certifications, index) => ({
    id: index + 1,
    ...certifications,
  })
);

export const CERTIFICATION_CATEGORIES = [
  "All",
  ...new Set(
    Object.entries(
      CERTIFICATIONS.reduce((acc, cert) => {
        const category = cert.category;
        if (acc[category]) acc[category]++;
        else acc[category] = 1;
        return acc;
      }, {} as Record<string, number>)
    )
      .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
      .map(([category]) => category)
  ),
];
